schema_name: Model Trust Manifest
schema_version: mtm-v0.1

required_fields:
  - mtm_version
  - model_name
  - model_description
  - aathman_fingerprint
  - intended_use
  - allowed_domains
  - prohibited_uses
  - owner
  - contact
  - created_at
  - updated_at

field_definitions:
  mtm_version:
    type: string
    description: Must be "mtm-v0.1"

  model_name:
    type: string
    description: Human-readable model name

  model_description:
    type: string
    description: Short description of the model

  aathman_fingerprint:
    type: string
    description: Hex fingerprint from Aathman Core

  intended_use:
    type: string
    description: Declared intended usage

  allowed_domains:
    type: list
    description: Allowed deployment contexts

  prohibited_uses:
    type: list
    description: Explicitly forbidden uses

  owner:
    type: string
    description: Responsible organization or team

  contact:
    type: string
    description: Contact information for accountability

  created_at:
    type: string
    description: ISO8601 timestamp

  updated_at:
    type: string
    description: ISO8601 timestamp

optional_fields:
  deployment_constraints:
    offline_only:
      type: boolean
    no_user_facing_output:
      type: boolean
    requires_human_review:
      type: boolean

validation_rules:
  - updated_at must not be earlier than created_at
  - No unknown top-level fields allowed
  - deployment_constraints keys must be whitelisted

non_goals:
  - Does not verify fingerprints
  - Does not enforce policy
  - Does not assess safety or performance
